### ISSUE TITLE
Provide way/suggestion how to add hidden ID to suggestion list and field

### ISSUE THREAD

**Issue by markusweisssiemens** [maxschuster/Vaadin-AutocompleteTextField#12]
Following scenario:

List and also selected entry should contain users and show something like:

firstname, lastname (department)

but for querying data and selecting data every user has an unique ID.

This ID should not be shown, but used inside the converter, because searching (e.g. in a database) by the display text is not a very good solution and even could have no unique result.

Do you have any suggestion how this can be done by extending / changing this component?

**Comment by maxschuster** [comment]
Hi,

This goes against the goal of this add-on. It's designed to behave like a normal TextField with a String as value.

Maybe you can use another add-on like [AutocompleteField for Vaadin](https://vaadin.com/directory#!addon/autocompletefield-for-vaadin) or [Viritins](https://vaadin.com/directory#!addon/viritin) LazyComboBox.

They both allow you to have a label connected to any object.
