### ISSUE TITLE
Using arrows on keyboard moves selection out of selection list

### ISSUE THREAD

**Issue by jamesswee** [maxschuster/Vaadin-AutocompleteTextField#13]
Hi
Nice fast add on!
As stated in the title if I start scrolling down the list using the keyboard arrow keys the selected element disappears out of the bottom of the suggestion list so you cannot see it anymore, you can then move the scrollbar (with the mouse) to see it.
I would expect the suggestion list to start scrolling when you get to the bottom of the visible part of it.
Is there any work around for this?

Also you can move the selection down past the last item in the list with the arrow keys which doesnt look normal

Thanks
James

**Comment by maxschuster** [comment]
Hi James,

which browser and OS are you using? I have tried it with Google Chrome, Safari and Firefox on macOS. I can change the selected item by using the arrow keys and the box will scroll to keep the currently selected visible. If I reach the end of the list the selection will move to the first item again and the box will scroll as well.

**Comment by jamesswee** [comment]
Hi Max
I have tested again today and I DO NOT have this problem now - weird. I am using windows 10 and Firefox 51.01 and Chrome 55.0..... maybe my system was having a glitch the other day?
The keyboard arrows behave as you describe them
Thanks for the reply
