### ISSUE TITLE
Demo page is down

### ISSUE THREAD

**Issue by kiru** [maxschuster/Vaadin-AutocompleteTextField#15]
I get a 502 no such environment message:

https://maxschuster.jelastic.servint.net/AutocompleteTextField/

**Comment by maxschuster** [comment]
Thank you for reminding me. I was using the free hosting of Vaadin add-ons on that site, but it does not seem to work anymore and I forgot to move my older add-ons. 😉 

I moved it to another server now: https://vaadin.maxschuster.eu/AutocompleteTextField/

**Comment by kiru** [comment]
Awesome, thank you.
