### ISSUE TITLE
getValue() on the field is not returning the selected value

### ISSUE THREAD

**Issue by Prady220** [maxschuster/Vaadin-AutocompleteTextField#16]
getValue() on the autocomplete text field is returning the value typed in for search instead of the selected value. This issue can be seen in all the browsers except in Firefox and Chrome.

**Comment by maxschuster** [comment]
Thank you for reporting this issue.

I'll investigate it.

**Comment by maxschuster** [comment]
I have upgraded the online demo with a fix: https://vaadin.maxschuster.eu/AutocompleteTextField/

**Comment by pradeep220** [comment]
Thank you for providing a fix in short notice

**Comment by Prady220** [comment]
I found an issue with the fix which I explained in detail at https://github.com/maxschuster/Vaadin-AutocompleteTextField/commit/29d145f6a9cf29f903eace3a61a82cf7783ca106

**Comment by maxschuster** [comment]
Did you have time to test, what I suggested [here](https://github.com/maxschuster/Vaadin-AutocompleteTextField/commit/29d145f6a9cf29f903eace3a61a82cf7783ca106#commitcomment-23422789)?

**Comment by pradeep220** [comment]
The fix is working. I messed up my test case. Also, instead of value change listener (it didnt work even with fix), I have used shortcut listener for Enter key, utilized .getValue() from text field and it worked on all browsers.

**Comment by maxschuster** [comment]
I will close this issue then. Please open another issue, if you still have issues with the value change listener.

**Comment by maxschuster** [comment]
Updated version 3.0-alpha-2 is available in the Vaadin Directory
