### ISSUE TITLE
AutocompleteSuggestion braucht eine ID

### ISSUE THREAD

**Issue by db0x** [maxschuster/Vaadin-AutocompleteTextField#2]
Hi,

es wäre gut, wenn AutocompleteSuggestion eine ID bekommt ( nach Möglichkeit java.util.UUID )

ansonsten kann ich nur sagen :+1: .. die Komponente überzeugt

**Comment by maxschuster** [comment]
Hey,

danke für das Lob! Möchtest du den Vorschlag anhand der UUID auf dem Server identifizieren? Das Add-on ist eigentlich nur dafür ausgelegt das TextField mit einem Wert zu befüllen, damit es sich weiterhin wie ein normales TextField verhält. Das heißt, dass z.B. auch Werte zulässig sind, die nicht Vorgeschlagen wurden. Der Wert des TextFeldes kann dann mit einem Converter weiterverarbeitet werden.

**Comment by db0x** [comment]
Hi,

genau, was du beschreibst möchte ich... also einen Vorschlag in einer Datenquelle identifizieren, wenn es ihn nicht gibt reagiere ich darauf.

Ich hatte gestern mal probiert wie sich das Textfeld mit dynamischer Quelle verhält, also bei jeder Suche wird die Liste der Vorschläge neu erzeugt -> geht super :+1: aber ich muss den Vorschlag identifizieren können 

dabei soll es so bleiben wie es ist, nämlich ein Textfeld

**Comment by maxschuster** [comment]
Dann schau dir mal dieses Add-on an: https://vaadin.com/directory#!addon/autocompletefield-for-vaadin
Ich verwende es auch in einem Projekt.

Es verbindet den Vorschlag auf dem Server mit einem Objekt. Jedoch muss der User den Vorschlag wirklich auswählen (per Maus, Touch oder Tastatur). Das kann für den User verwirrend sein. Und das TextField verschickt auch keine TextChange- und ValueChangeEvents

**Comment by db0x** [comment]
hatte ich schon probiert, aber das hat mich an den Rand der Verzweiflung gebracht ... dein Addon  tut einfach, was es soll :) ich brauche nur eine eindeutige ID im Vorschlag ... dann bin ich echt glücklich 

Aus welchem Grund ist AutocompleteSuggestion final ? .. Wenn das nicht final wäre, dann könnt ich mir selbst helfen ;)

**Comment by maxschuster** [comment]
Wie planst du die ausgewählte UUID zurück an den Server zu übermitteln?

**Comment by db0x** [comment]
ich glaube ich verstehe, was du meinst ... 
```java
 languageField.addValueChangeListener(e -> {
            String text = "Value changed to: " + e.getProperty().getValue();
            Notification notification = new Notification(
                    text, Notification.Type.TRAY_NOTIFICATION);
            notification.setPosition(Position.BOTTOM_LEFT);
            notification.show(Page.getCurrent());
        });
```

e.getProperty().getValue(); << ich nehme mal an, an der Stelle kommt man nur an den String und nicht an den Rest ( also Desc / Icon / etc. ) ... das wäre schade, dnn nutzt ne UUID in der Tat nichts ... 

wenn du magst können wir da gern mal im skype drüber diskutieren :)

**Comment by db0x** [comment]
Durch eine Ableitung von CollectionSuggestionProvider konnte ich das gewünschte Verhalten erreichen. mein CollectionSuggestionProvider hat eine Map von Wert zu ID und ich hole mir die ID anhand des Wertes aus dem Provider.
