### ISSUE TITLE
How can I configure the minimal length of the query?

### ISSUE THREAD

**Issue by dk2k** [maxschuster/Vaadin-AutocompleteTextField#30]
I can see, that suggestions get requested when the length reaches value 3. However, I can't find this value in the sources. Are there any means to change this value? Any information can help. Even if there is no public API, I probably still can use Reflection. If there are no means to configure it, can you please compose this enhancement? 
Important, I still use version 1.0-alpha-4 :)

**Comment by maxschuster** [comment]
Did you try `AutocompleteTextField.setMinChars(int)` ?

**Comment by dk2k** [comment]
Thanks!
