### ISSUE TITLE
Add-on doesn't work

### ISSUE THREAD

**Issue by denis-anisimov** [maxschuster/Vaadin-AutocompleteTextField#5]
Use attached project.
Type "a" in the textfield. Nothing happens. Suggestions don't appear.
[test.zip](https://github.com/maxschuster/Vaadin-AutocompleteTextField/files/134485/test.zip)

**Comment by maxschuster** [comment]
Hi Denis,

you are missing this setting:
```java
field.setMinChars(1);
```
By default, the threshold for auto completion is three letters.

**Comment by denis-anisimov** [comment]
Hi Max.
OK, you are right, my bad.
But it's not obvious. 
At least online demo works with one char but example source code on add-on page doesn't contain any mention about this. Would be good to add it to clarify this issue.

**Comment by maxschuster** [comment]
Thank you for your suggestion.
I have added the available configuration options to the example code in the Directory:
```java
// ===============================
// Available configuration options
// ===============================
field.setCache(true) // Client side should cache suggestions
field.setDelay(150) // Delay before sending a query to the server
field.setItemAsHtml(false) // Suggestions contain html formating. If true, make sure that the html is save to use!
field.setMinChars(3) // The required value length to trigger a query
field.setScrollBehavior(ScrollBehavior.NONE) // The method that should be used to compensate scrolling of the page
field.setSuggestionLimit(0) // The max amount of suggestions send to the client. If the limit is >= 0 no limit is applied
```

**Comment by denis-anisimov** [comment]
Very good. 
Thanks!
