### ISSUE TITLE
Ability to add suggestion select listener

### ISSUE THREAD

**Issue by tistvan** [maxschuster/Vaadin-AutocompleteTextField#8]
I would like to implement a feature which fills other textfields when the user picks a suggestion. Currently i am not able to do that with this addon. Ability to add suggestion select listener would be great.

**Comment by dk2k** [comment]
I agree with tistvan. It's a must have.

**Comment by maxschuster** [comment]
In fact, I'm working on it right now ;-)

**Comment by dk2k** [comment]
https://blog.oio.de/2015/01/17/write-simple-auto-complete-combobox-vaadin/ may be helpful ;-)

**Comment by maxschuster** [comment]
This add-on is designed to be a TextField with a String as value.
https://github.com/maxschuster/Vaadin-AutocompleteTextField/issues/12#issuecomment-277391947

I'm adding a select event that will get triggered when the user actively selects a suggestion by clicking or pressing enter. The event won't get triggered if the spells out the word without selecting a suggestion.

**Comment by dk2k** [comment]
Is it possible to wrap in SelectionEvent the actual selected Object (in common case it's an Object with an overriden toString() method)?

**Comment by tistvan** [comment]
>  The event won't get triggered if the spells out the word without selecting a suggestion.

Perfect!

**Comment by maxschuster** [comment]
I've updated the [online demo](https://vaadin.maxschuster.eu/AutocompleteTextField/) with an "Add SelectListener" checkbox. If you enable it, you should see a notification in the lower right corner of the screen, when you select a suggestion.

You can find the new source code in the [onselect branch](https://github.com/maxschuster/Vaadin-AutocompleteTextField/tree/onselect).

**Comment by dk2k** [comment]
Great job!
Are you going to back port this enhancement to versions 1 and 2? Do you need help with that? We are currently using version 1 and will probably upgrade to 2 if it's compliant with vaadin 7.9. Version 3 requires vaadin 8 and that's not an option for us so far.

**Comment by maxschuster** [comment]
I'm not sure when I'll have the time to do it. If created issue #20 for the back port.

**Comment by maxschuster** [comment]
Updated version 3.0-alpha-2 is available in the Vaadin Directory
